name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for auch
      run: |
        cd auth
        docker build -t dredfort/rupl-auth:latest .
        docker push dredfort/rupl-auth:latest

    - name: Build and push Docker image for profile
      run: |
        cd profile
        docker build -t dredfort/rupl-profile:latest .
        docker push dredfort/rupl-profile:latest
